# Generated by Django 3.2 on 2021-06-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210602_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='is_liked',
            field=models.BooleanField(default=None),
        ),
    ]
