# Generated by Django 3.2 on 2021-06-02 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_useroutfitrelation_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='fans',
        ),
        migrations.AddField(
            model_name='outfit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='outfits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserOutfitRelation',
        ),
    ]
