# Generated by Django 3.2 on 2021-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_outfit_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='is_liked',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Поставил лайк'),
        ),
    ]
