# Generated by Django 3.2 on 2021-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outfit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outfit',
            options={'verbose_name': 'Образ', 'verbose_name_plural': 'Образы'},
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='content',
        ),
        migrations.AddField(
            model_name='outfit',
            name='title',
            field=models.CharField(default=0, max_length=40, verbose_name='Образ'),
        ),
    ]
