# Generated by Django 3.2 on 2021-05-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210512_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outfit',
        ),
    ]
